### ISSUE TITLE
What is this repository about?

### ISSUE THREAD

**Issue by ABSphreak** [deepankur797/katacoda-scenarios#1]
_Want to know more about this **KataCoda scenarios**. Please delete this issue._ 😁😁😁

**Comment by deepankur797** [comment]
didn't see this earlier, but this repo is all about making your own scenarios of various tasks on the Katacoda website. For more info check out this [link](https://www.katacoda.com/create). I will make some of these in the future.

**Comment by ABSphreak** [comment]
### Awesome!
